### ISSUE TITLE
Add `--url` cli option to `pierone latest` action

### ISSUE THREAD

**Issue by elgalu** [zalando-stups/pierone-cli#16]
New feature request:

```sh
pierone latest --url $MY_OPEN_SOURCE_PIERONE $TEAM $ARTIFACT
#=> Error: no such option: --url
```

Else it always seem to look in my $PRIVATE pierone server, i.e. looks at the config files but is inconvenient to be changing it when working on different pierone servers.

**Comment by hjacobs** [comment]
True, we have to do something about that (also for all the other commands)

**Comment by sarnowski** [comment]
Not only `--url` but also the `-U` option must be supported consistently across all our CLIs.

**Comment by hjacobs** [comment]
Fixed in https://github.com/zalando-stups/pierone-cli/releases/tag/1.0.7

The "-U" option will not be added as "pierone" now uses the generic "zign.api.get_token()" function which allows configuring the user name in Zign.
