### ISSUE TITLE
Document how to fetch latest version of the image

### ISSUE THREAD

**Issue by valgog** [zalando-stups/pierone-cli#18]
I am struggling to understand how the CLI works. The `--help` does not really help.

I want to get the latest available version of the `stups/zmon-scheduler` image, how to do that?

I tried all the combinations already, the only thing that I managed to get working is the `pierone artifacts stups`

**Comment by hjacobs** [comment]
@valgog you can use the "latest" command:

```
$ pierone latest -h
Usage: pierone latest [OPTIONS] TEAM ARTIFACT

  Get latest tag/version of a specific artifact

Options:
  -o, --output [text|json|tsv]  Use alternative output format
  -h, --help                    Show this message and exit.
```

Example usage:

```
$ pierone latest stups pierone
1.8.4
```

**Comment by hjacobs** [comment]
Added example "latest" call here: http://docs.stups.io/en/latest/components/pierone.html#command-line-client
