### ISSUE TITLE
pierone tags command does not accept team names with dashes

### ISSUE THREAD

**Issue by ChristianLohmann** [zalando-stups/pierone-cli#19]
When trying to list tags for teams which include dashes for example, the cli complains with : ```Error: Invalid value for "team": Team ID must satisfy regular expression pattern "[a-z][a-z0-9]+"```

**Comment by hjacobs** [comment]
OK, agreed, we have a mismatch between theoretic constraint and reality here :smirk:

**Comment by hjacobs** [comment]
Fixed in https://github.com/zalando-stups/pierone-cli/releases/tag/1.0.7
