### ISSUE TITLE
pierone url is fixed in config when passed as --url param

### ISSUE THREAD

**Issue by drummerwolli** [zalando-stups/pierone-cli#23]
https://github.com/zalando-stups/pierone-cli/blob/master/pierone/cli.py#L75

the setting gets saved, also when the url gets passed via --url ... in my understanding a param is a runtime change and should not be permanently saved.

reconstruction:

1) pierone login # should login into your standard config file repo
2) pierone login --url some.pierone.url.example.org # will login into the other repo AND save this setting in your config
3) pierone login # i expect a login into the repo from 1), but it logs into 2)

or am i understanding it conceptually wrong?

**Comment by hjacobs** [comment]
True, this behavior is not intended --- I experience the same issue when toggling between Pier One and the OS registry :disappointed:

**Comment by hjacobs** [comment]
Fixed in https://github.com/zalando-stups/pierone-cli/releases/tag/1.0.14

**Comment by drummerwolli** [comment]
:thumbsup:
