### ISSUE TITLE
pierone login --url is ignored (on OS X)

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando-stups/pierone-cli#26]
Steps to reproduce:
1. have at least 2 different registries 
2. login to one of them (i..e registry_a)
3. try to login to another one using pierone login --url <registry_b_url>
4. try to query something, i.e. pierone tags ...
The last step will produce artifacts from the registry_a, more specifically, from the registry mentioned at ~/Library/Application Support/pierone/pierone.yaml
The pierone login --url does not overwrite this file with the new registry name.
The one way for me to switch the registry is to change the URL in this file manually.

**Comment by hjacobs** [comment]
I think this behavior is desired (we changed it with #23). The "--url" option only affects the current execution, i.e. you can do:

```
pierone tags --url myregistry
