### ISSUE TITLE
Return propper errorcode when client is unauthorized

### ISSUE THREAD

**Issue by MALPI** [zalando-stups/pierone-cli#27]
When trying to push an artifact and the client is currently not authorized it results in

```
The push refers to a repository [pierone.stups.zalan.do/team/app] (len: 1)
hash: Preparing
<nil>
```

An error message like **unauthorized** would make the error more obvious.

**Comment by hjacobs** [comment]
@MALPI this is sadly not a bug in our CLI tool, but in Docker itself, see https://github.com/docker/docker/issues/18569
