### ISSUE TITLE
PierOne fails with clickclick ImportError

### ISSUE THREAD

**Issue by pgronkiewicz** [zalando-stups/pierone-cli#29]
`Traceback (most recent call last):
  File "/usr/local/bin/pierone", line 7, in <module>
    from pierone.cli import main
  File "/usr/local/lib/python3.4/dist-packages/pierone/cli.py", line 9, in <module>
    import zign.api
  File "/usr/local/lib/python3.4/dist-packages/zign/api.py", line 2, in <module>
    from clickclick import error, info, UrlType
ImportError: cannot import name 'UrlType'
The command '/bin/sh -c pierone --version' returned a non-zero code: 1`

It is resolved by manually adding beforehand:
`pip3 install --upgrade clickclick`

Tested inside docker image based on ubuntu:wily

**Comment by rafaelcaricio** [comment]
You probably uninstalled clickclick by mistake. Because the requirements.txt of this project (which is used to build the conf for the package in pypi) includes [`clickclick`](https://github.com/zalando-stups/pierone-cli/blob/master/requirements.txt#L1).
