### ISSUE TITLE
Limit shown tags by default

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/pierone-cli#35]
$ pierone tags myteam

This can potentially output a very huge lists of different artifacts and versions. Even filtering for an artifact can still be a very big list. By default, one only cares about the latest or the last couple of recent tags.

My proposal is to change the default behaviour of `pierone tags` to only show the last 3(?) versions of each artifact with a command line option to either have another number of versions or unlimited versions:

Command | Result
------------ | --------
`pierone tags myteam` | show last 3 versions of each artifact
`pierone tags myteam --limit=5` | show last 5 versions of each artifact
`pierone tags myteam --limit=0` | show all versions of each artifact

**Comment by hjacobs** [comment]
This was already released in https://github.com/zalando-stups/pierone-cli/releases/tag/1.0.28
