### ISSUE TITLE
Store Clair URLs in combination with PierOne URLs

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/pierone-cli#39]
Currently the following command will not work:

    $ pierone cves --url https://registry.opensource.zalan.do/ stups openjdk 8-24

The problem here is that I am not reading from my default registry but it still takes my default Clair URL which is wrong for this registry. The CLI should store the Clair URL in conjunction with the registry URL:

    https://registry1 -> https://clair1
    https://registry2 -> https://clair2

**Comment by hjacobs** [comment]
@sarnowski better idea: why not configure the Clair URL in Pier One and expose it on same well-known URL path?

**Comment by sarnowski** [comment]
Sure that is an option, I just extended the implementation that was already chosen. When switching the implementation, one can also go the more "REST" way and provide the created URL:

```json
  {
    "name": "16.04-31",
    "created": "2016-06-01T15:27:46.724Z",
    "created_by": "stups_stups-go",
    "image": "sha256:5fd5ecf3346aade4bb0cc4999e980d293492b94aeb38028e5a734dec04caf2d6",
    "clair_id": "sha256:10ed777391096f869709bbd8328280a944733e2579abc6f8c86950783ca1a5e5",
    "severity_fix_available": "clair:NoCVEsFound",
    "severity_no_fix_available": "Medium",
    "clair_details": "https://clair.opensource.zalan.do/v1/layers/sha256:10ed777391096f869709bbd8328280a944733e2579abc6f8c86950783ca1a5e5"
  }
```

**Comment by dryewo** [comment]
This will require explicitly providing clair url in pierone config, because pierone does not interact with clair directly, only via queues.

**Comment by sarnowski** [comment]
Yes.
