### ISSUE TITLE
pierone login doesn't care if there is something already at `.dockercfg`

### ISSUE THREAD

**Issue by elgalu** [zalando-stups/pierone-cli#4]
pierone login doesn't care if there is something already at `.dockercfg` like my "https://index.docker.io/v1/" credentials, simply wipes the json file instead of adding/updating my private pierone docker registry.

**Comment by hjacobs** [comment]
Hmm, that's not right -- Pier One CLI will *update* the ~/.dockercfg and not simply wipe it, please check the code here: https://github.com/zalando-stups/pierone-cli/blob/master/pierone/api.py#L51

**Comment by elgalu** [comment]
`yaml.safe_load` ? idk python but `~/.dockercfg` looks json to me then the `try` fails and `dockercfg = {}` is always executed.

**Comment by hjacobs** [comment]
@elgalu JSON is always valid YAML
the YAML parser is a bit more relaxed, so I'm using it

**Comment by elgalu** [comment]
Intersting :D

Ok, will retest and let you know.

**Comment by elgalu** [comment]
Ok, retested again with these versions:

Senza 0.46
Mai 0.14
Piu 0.10
Pier One CLI 0.9
Zign 0.12

State 0: I can push to public docker.io

`jq '.' ~/.dockercfg`

```json
{
    "https://index.docker.io/v1/": {
        "auth": "ZWxnYWxXXXXXXXXXXXXX==",
        "email": "leoXXXXXXX@gmail.com"
    }
}
```

State 1: after `pierone login`:

`jq '.' ~/.dockercfg`

```json
{
    "pierone.stups.zalan.do": {
        "email": "no-mail-required@example.org",
        "auth": "b2F1dGXXXXXXXXXXXXXXXXXXXxx=="
    }
}
```

So docker.io config is gone.

**Comment by hjacobs** [comment]
hmm, I can't reproduce the problem on my machine, but I will add a unit test for Travis CI

**Comment by hjacobs** [comment]
@elgalu Travis CI tells me that it should work not only on my machine: https://travis-ci.org/zalando-stups/pierone-cli
