### ISSUE TITLE
no basic auth credentials

### ISSUE THREAD

**Issue by dmigo** [zalando-stups/pierone-cli#58]
Today I had an auth issue. While trying to do `docker push` I was getting the following log:

    ➜ pierone login             
    Getting OAuth2 token "pierone".. OK
    Storing Docker client configuration in /Users/whoever/.docker/config.json.. OK
    ➜ docker push myrepo/...
    The push refers to a repository [myrepo/...]
    a5f591aacc10: Preparing 
    ...
    cb11ba605400: Waiting 
    no basic auth credentials

Recreating `~/config.json` saved me.  
There was `"credsStore": "osxkeychain"` setting In the previous version of the `~/config.json` which was causing me troubles.

BTW 
mac os 10.12.3
pierone cli 1.1.27
docker 17.06.0-ce, build 02c1d87

**Comment by hjacobs** [comment]
As this apparently happens "more frequently" in the past weeks (only on Mac), we should investigate...

**Comment by mvalkon** [comment]
Occurs somewhat frequently for me as well on OS X.

**Comment by luisfarzati** [comment]
Same here, Mac OS Sierra:

```
{
    "auths": {
        "https://pierone.stups.zalan.do": {
            "auth": "xxx",
            "email": "no-mail-required@example.org"
        },
        "https://registry-write.opensource.zalan.do": {
            "email": "no-mail-required@example.org",
            "auth": "xxx"
        },
        "https://registry.opensource.zalan.do": {
            "email": "no-mail-required@example.org",
            "auth": "xxx"
        }
    },
    "credsStore": "osxkeychain"
}
```

**Comment by luisfarzati** [comment]
Some research we just did with @Raffo : https://github.com/docker/for-mac/issues/1826
