### ISSUE TITLE
scm-source sanity check for mark trusted

### ISSUE THREAD

**Issue by lotharschulz** [zalando-stups/pierone-cli#65]
Marking an image trusted shall be **only** possible under these conditions:

- is scm-source info present
- is it syntactically correct, according to https://stups.readthedocs.io/en/latest/user-guide/application-development.html#scm-source-json
- is url a valid git url?
- is revision a full commit hash (not an abbreviated one)
- git status was clean (empty)

**Comment by lotharschulz** [comment]
https://github.com/zalando-stups/pierone-cli/issues/64#issuecomment-398010693 follow up

**Comment by juhmelo** [comment]
this is implemented on pierone side https://github.bus.zalan.do/automata/piertwo/pull/18
