### ISSUE TITLE
Recurring issue with Docker auth

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/pierone-cli#81]
There is a recurring issue (sporadically popping up in Zalando support chats) about `docker pull` not working after doing `pierone login` --- usually users have to delete `~/.docker` and it works again. Let's fix this once and for all.

**Comment by pmeinhardt** [comment]
IMHO pierone should not meddle with system-wide config files at all.

Instead it could act as a wrapper and use its own config directory (see the [docker `--config` flag](https://docs.docker.com/engine/reference/commandline/cli/#configuration-files)) so docker will continue to work as expected. I don't have a clear idea of what the command-line interface would look like then but I think an approach along those lines would be much cleaner 🤔 

Just my 2 cents though 🤷‍♂

**Comment by pmeinhardt** [comment]
One common pattern for many command-line tools is to expose an `init` subcommand to initialize the shell environment. E.g.

```sh
eval $(pierone init)
```

This could take care of setting up the environment and do something like `export DOCKER_CONFIG=~/.pierone/docker`
