### ISSUE TITLE
Login breaks Docker config

### ISSUE THREAD

**Issue by pmeinhardt** [zalando-stups/pierone-cli#87]
Executing `pierone login` breaks `~/.docker/config.json`.

In particular, it sets an empty `credHelper`:

```json
{
  "auths": {
    "https://pierone.stups.zalan.do": {
      "auth": "…",
      "email": "no-mail-required@example.org"
    }
  },
  "credHelpers": {
    "pierone.stups.zalan.do": ""
  }
}
```

After `pierone login`, on attempting to `docker pull` an image, it will fail:

```
Error response from daemon: Get https://pierone.stups.zalan.do/v2/…/manifests/latest: no basic auth credentials
```

Removing the empty `credHelpers` entry for `"pierone.stups.zalan.do"` fixes the problem.

I am using:

```
$ docker --version
Docker version 19.03.5, build 633a0ea
```

**Comment by aermakov-zalando** [comment]
Fixed in #93.
